name: Publish JSDoc documentation in Node.js app in GitHub Pages

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Optional build step
        run: npm run build --if-present
      - name: Generate JSDoc
        run: npm run docs
      - name: Create artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: public
          path: ./public

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to gh-pages # Deploy documentation to gh-pages branch
        uses: actions/checkout@v4.1.5
        with:
          ref: gh-pages
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clear existing content (optional)
        run: rm -rf ./public  # This will remove all existing files in the gh-pages branch
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: public
          path: ./public
      - name: Commit changes
        run: |
          git config credential.helper store
          git config credential.helper 'store -s {{ GITHUB_ACTOR }}'
          echo "https://darthcav:{{ secrets.GH_PAGES_TOKEN }}@github.com" > ~/.git-credentials
          git config user.name {{ GITHUB_ACTOR }}
          git config user.email {{ secrets.ACTOR_EMAIL }}
          git add .
          git commit -m "Deploy JSDoc documentation"
      - name: Push to gh-pages
        run: git push origin gh-pages

